### ISSUE TITLE
სლაიდერი: ჩანაწერის სტატუსი

### ISSUE THREAD

**Issue by Mariam-Benashvili** [teimuraz-kevlishvili/XCMS#16]
ახალი ჩანაწერის დამატებისას სტატუსი აქაც გამორთულია default-ად. უნდა იყოს ჩართული.

გარდა ამისა, ლისთინგის გვერდზე აღარ ხდება სტატუსის ცვლილება იმ შემთხვევაში თუ დამატებისას მითითებული გქონდა სტატუსი "გამორთული"
![image](https://user-images.githubusercontent.com/12964283/32312601-13efa668-bfb8-11e7-93ed-993daa55c979.png)

**Comment by davidjije** [comment]
ახალი ჩანაწერის დამატებისას უკვე default-ად ჩართულია სტატუსი, ხოლო რაც შეეხება სტატუსის ცვლილებას, არ მუშაობს მხოლოდ მაშინ, როდესაც ელემენტს ID აქვს 0.  test-ის დამატების დროს, ბაზაში ID-ის Auto Increment იყო გათიშული, რომელიც ცალკე ბაგია, მე რა table-ბთანაც მქონდა შეხება, რაღაც პერიოდის შემდეგ ავტომატურად უუქმდება Auto Increment-ი.
