### ISSUE TITLE
გლობალური ელემენტი: სია (List)

### ISSUE THREAD

**Issue by Mariam-Benashvili** [teimuraz-kevlishvili/XCMS#4]
სისტემაში უნდა დავამატოთ გლობალურად სიის ელემენტი, გათვალისწინებული უნდა იყოს მაქსიმალურად ყველა შესაძლო შემთხვევისათვის.

**Comment by froel1** [comment]
ელემენტი გაკეთებულია , გასატესტია სხვა მხრივ მუშაობს , აქვს 4 ატრიბუტი key_field , value_field სიის დაგენერირების დროს  რა პრინციპიტ გაეწეროს მნიშვნელობები , value_field;
ასევე table , იმ შემთხვევაში და განსხვავებული პარამეტრებით არ ხდება ინფორმაციის წამოღება ბაზიდან (ფილტრავს მხოლოდ სტატუსზე) 
და query თუ საკუთარი სქლ ბრძანების გაშვება გჭირდება 

`<field name="title" type="list" default="" key_field="id" value_field="title" table="mediamanager" label="title" class="" />`

**Comment by froel1** [comment]
ასევე ელემენტის გამოყენება შეიძლება გრიდზე იგივე პრინციპით
