### ISSUE TITLE
გლობალური ელემენტი: ასარჩევი ველი (Radio)

### ISSUE THREAD

**Issue by Mariam-Benashvili** [teimuraz-kevlishvili/XCMS#5]

**Comment by froel1** [comment]
რადიო ელემენტი რომელიც xml(option) მიხედვიტ დაგენერირდება აქვს შემდეგი რპობლემები ბიბლიოთეკაში , 
`public function XPathChildren()
	{
		echo '<pre><pre>';
		print_r( $this );
		echo '</pre><b>FILE:</b> ' . __FILE__ . '     <b>Line:</b> ' . __LINE__ . '</pre>' . "\n";
		die;

		$items = C::_( $Key, $this );
		if ( is_array( $items ) )
		{
			return $items;
		}
		else if ( !empty( $items ) )
		{
			return array( $items );
		}
		return $Default;

	}`

და ეს : 
`public function Children( $ns = null, $is_prefix = false )
	{
		echo '<pre><pre>';
		print_r( $this );
		echo '</pre><b>FILE:</b> ' . __FILE__ . '     <b>Line:</b> ' . __LINE__ . '</pre>' . "\n";
		die;

	}`

ვცადო წინა სისტემის მიხედვით დამუშავება ? @teimuraz-kevlishvili

**Comment by froel1** [comment]
xml ის <option> ებს იღებს თუმცა ჩაილდ ოფშენებში გაწერილ მნიშვნელობებს არ კითხულობს

**Comment by teimuraz-kevlishvili** [comment]
უკვე დავამუშავე რადიოს ელემენტი, მოგვიანებით ავტვირთავ

**Comment by teimuraz-kevlishvili** [comment]
ელემენტი ატვირთულია.
