### ISSUE TITLE
სურათის ელემენტი ლისთინგისათვის

### ISSUE THREAD

**Issue by Mariam-Benashvili** [teimuraz-kevlishvili/XCMS#7]
გრიდისათვის გავაკეთოთ ერთი ელემენტი სადაც გამოვა ამ ჩანაწერზე მიმაგრებული სურათი პატარა ზომაში დამუშავებული: მაგ: 80X80px. 
![image](https://user-images.githubusercontent.com/12964283/32272180-5f7d9452-bf16-11e7-8ddf-ce7c7d2354aa.png)
კლიკზე უნდა ამოვიდეს პოპაპში. ამ ელემენტს გამოვიყენებთ: მედია მენეჯერში, სლაიდერის კონპონენტში... @AnriDaiki

**Comment by sprom** [comment]
დავამატე პოპაპი თუ ესე გვინდა გადახედეთ :)

**Comment by teimuraz-kevlishvili** [comment]
@sprom ეს პოპაპი უნდა იხურებოდეს ნებისმიერ ადგილზე დაკლიკებით!

**Comment by sprom** [comment]
გვერდძე დაკლიკებისასაც ვხურავ გადავაკეთე
